using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;

namespace Mod_Installer___Manager
{
    public partial class XmlCreator : Form
    {
        public XmlCreator()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            settings.NewLineOnAttributes = true;
            XmlWriter writer = XmlWriter.Create("mod.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("Generated By Aeros' Mod Installer");
            writer.WriteStartElement("mod-details");
            writer.WriteStartElement("dropzone");
            writer.WriteAttributeString("type", modType.Text);
            /*
            writer.WriteAttributeString("multi-option", "false");
            writer.WriteAttributeString("first-option", "");
            writer.WriteAttributeString("second-option", "");
            writer.WriteAttributeString("third-option", "");
            writer.WriteAttributeString("fourth-option", "");
            */
            writer.WriteEndElement();
            writer.WriteStartElement("mod");
            writer.WriteAttributeString("id", modID.Text);
            writer.WriteAttributeString("modder", modderID.Text);
            writer.WriteAttributeString("ver", modVer.Text);
            writer.WriteAttributeString("dir", modDir.Text);
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
            MessageBox.Show("Created A Mod XML File :)");
        }
    }
}
