using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace Template_Generator
{
    class Program
    {
        static void Main(string[] args)
        {
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            settings.NewLineOnAttributes = true;
            XmlWriter writer = XmlWriter.Create("mod.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("Generated By Aeros' Mod Installer");
            writer.WriteStartElement("mod-details");
            writer.WriteStartElement("dropzone");
            Console.WriteLine("dropzone or dropzone_sky_fortress");
            string type = Console.ReadLine();
            writer.WriteAttributeString("type", "dropzone_sky_fortress");
            writer.WriteAttributeString("multi-option", "false");
            writer.WriteAttributeString("first-option", "");
            writer.WriteAttributeString("second-option", "");
            writer.WriteAttributeString("third-option", "");
            writer.WriteAttributeString("fourth-option", "");
            writer.WriteEndElement();
            writer.WriteStartElement("mod");
            writer.WriteAttributeString("id", "Better Wingsuit");
            writer.WriteAttributeString("modder", "Aeros");
            writer.WriteAttributeString("ver", "0.1A");
            writer.WriteAttributeString("dir", "aeros_wingsuit");
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
        }
    }
}
